require("@rails/ujs").start();
require("turbolinks").start();
require("@rails/activestorage").start();
require("channels");
require("jquery");
global.$ = jQuery;
require("turbolinks");
require("popper.js");
require("bootstrap");
require("video.js");
require("magnific-popup");
require("owl.carousel");
require("packs/custom");
require("packs/users");
require("packs/courses");
